In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/patient_dataset.csv", header = None)
df.head()
# first column is the feature: age
# we are trying to use the age to predict whether
# the patient will recover from the disease (second column)

      0    1
0  10.0  1.0
1  67.0  0.0
2  28.0  1.0
3  49.0  1.0
4  58.0  0.0

In [4]:
num_patients = len(df)
print(num_patients)

28

In [5]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [6]:
# this method is called leave-one-out

total_score = 0
# start the total score at 0 and iterate through patients
for i in range(num_patients):
  # we get all the patients before i (0:i) and all the patients after (i+1:)
  # and combine them together as our training dataset
  train = pd.concat( [ df.iloc[:i], df.iloc[i+1:] ] )
  # then we have the testing sample
  test = df.iloc[i]
  # separate into X and y to train the model

  # colon before the comma means we are getting all of the rows
  # the range after the comma is the columns we want
  # for train_X we want all the columns before the last one
  train_X = train.iloc[:,:1]
  # and for train_y we want just the last column
  train_y = train.iloc[:,1]
  log_reg.fit(train_X, train_y)
  # if the predicted output is correct
  if (log_reg.predict( [ test.iloc[:1] ] ) == test[1]):
    total_score += 1
    # add one to the total score

print("Average score:", total_score / num_patients)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [7]:
df

       0    1
0   10.0  1.0
1   67.0  0.0
2   28.0  1.0
3   49.0  1.0
4   58.0  0.0
5   45.0  NaN
6    NaN  0.0
7   56.0  0.0
8   33.0  NaN
9    NaN  1.0
10  60.0  0.0
11  52.0  1.0
12   NaN  1.0
13  40.0  1.0
14  30.0  1.0
15  48.0  1.0
16   NaN  0.0
17  55.0  1.0
18  32.0  1.0
19   NaN  0.0
20  38.0  1.0
21   NaN  1.0
22  50.0  0.0
23  42.0  1.0
24   NaN  0.0
25  89.0  0.0
26   NaN  1.0
27  23.0  1.0

In [8]:
df = df.dropna()

df

       0    1
0   10.0  1.0
1   67.0  0.0
2   28.0  1.0
3   49.0  1.0
4   58.0  0.0
7   56.0  0.0
10  60.0  0.0
11  52.0  1.0
13  40.0  1.0
14  30.0  1.0
15  48.0  1.0
17  55.0  1.0
18  32.0  1.0
20  38.0  1.0
22  50.0  0.0
23  42.0  1.0
25  89.0  0.0
27  23.0  1.0

In [9]:
num_patients = len(df)
# this method is called leave-one-out

total_score = 0
# start the total score at 0 and iterate through patients
for i in range(num_patients):
  # we get all the patients before i (0:i) and all the patients after (i+1:)
  # and combine them together as our training dataset
  train = pd.concat( [ df.iloc[:i], df.iloc[i+1:] ] )
  # then we have the testing sample
  test = df.iloc[i]
  # separate into X and y to train the model

  # colon before the comma means we are getting all of the rows
  # the range after the comma is the columns we want
  # for train_X we want all the columns before the last one
  train_X = train.iloc[:,:1]
  # and for train_y we want just the last column
  train_y = train.iloc[:,1]
  log_reg.fit(train_X, train_y)
  # if the predicted output is correct
  if (log_reg.predict( [ test.iloc[:1] ] ) == test[1]):
    total_score += 1
    # add one to the total score

print("Average score:", total_score / num_patients)

Average score: 0.8888888888888888